# https://docs.travis-ci.com/user/languages/groovy/
language: groovy
jdk:
  - openjdk11

script: ./gradlew check --rerun-tasks

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
